name: Coding Standard & Static Analysis

on:
  workflow_dispatch:
    inputs:
      phive_keys:
        description: 'GPG key signatures for phive packages. Should be comma separated string "800d,d44d"'
        required: false
        default: 'CF1A108D0E7AE720,51C67305FFC2E5C0,12CE0F1D262429A5'
        type: string
  
permissions:
  contents: read

jobs:
  psalm:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        tools: phive, cs2pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Composer install
      run: composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist

    - name: Run psalm
      run: vendor/bin/psalm --output-format=github