name: Coding Standard & Static Analysis

on:
    push:
        paths:
        - '**.php'
  
permissions:
  contents: read

jobs:
  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Composer install
      uses: ramsey/composer-install@v2

    - name: Install Psalm phar
      run: |
        wget https://github.com/vimeo/psalm/releases/latest/download/psalm.phar
        chmod +x psalm.phar
        mv psalm.phar /usr/local/bin/psalm.phar

    - name: Run psalm
      if: always()
      run: psalm.phar --output-format=github
